name: Build and Release

on:
  push:
    tags:
      - "v*"   # runs only when you push a tag like v1.0.0

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        runtime: [linux-x64, win-x64]

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Publish
        run: dotnet publish -c Release -r ${{ matrix.runtime }} --self-contained true -p:PublishSingleFile=true -o ./publish/${{ matrix.runtime }}

      - name: Package build
        run: |
          cd publish/${{ matrix.runtime }}
          zip -r ../../BulkRecordTool-${{ matrix.runtime }}.zip .
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: BulkRecordTool-${{ matrix.runtime }}
          path: BulkRecordTool-${{ matrix.runtime }}.zip

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: BulkRecordTool-${{ matrix.runtime }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
